/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.liliangshan.web;

import org.junit.Test;

import static org.junit.Assert.*;

public class ApplicationTest {

    @Test
    public void test() {
    }
}
